### ISSUE TITLE
Move meta to be attached to the sources

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-layers-api#11]
The meta object that currently exists with the layergroup, and is used for populating the 'data' page in a frontend UI, is really just describing a source, not the layergroup.  

I recommend we move this config out of the layergroups, and add them to the source objects.  This way a layergroup can have more that one source, and each will bring its own meta along for the ride.

```
"meta":
  {
    "description": "NYC GIS Zoning Features June 2018, Bytes of the Big Apple",
    "url":
    [
      "https://www1.nyc.gov/site/planning/data-maps/open-data.page"
    ],
    "updated_at": "July 18th, 2018"
  }
```

**Comment by hannahkates** [comment]
- Make sure metadata is up to date in layers-api (table names, date, text description)
- Make sure metadata is being consumed and displayed properly in both CityMap and ZoLa.

**Comment by allthesignals** [comment]
So `layer-groups` are associated with sources through their `layers` - so it's really layers that contain the foreign key relationship. A layer-group can have many `sources` through its layers. 

I think this means for the sake of convenience we want the `layer-group` to contain the reference to the `source`:

<details><summary>JSON API Output</summary>

```
{
  "data": [
    {
      "type": "layer-groups",
      "id": "aerials",
      "attributes": {
        "id": "aerials",
        "legend": {
          "label": "Aerial Imagery",
          "tooltip": "Aerial Photos Raster Tiles provided by DoITT GIS"
        },
        "layer-visibility-type": "singleton",
        "meta": {
          "description": "NYC DoITT GIS Aerial Photography Tile Layers (TMS)",
          "url": [
            "https://maps.nyc.gov/tiles/"
          ],
          "updated-at": "n/a"
        }
      },
      "relationships": {
        "layers": {
          "data": [
            {
              "type": "layers",
              "id": "aerials-2016"
            },
          ]
        },
        "sources": {
          "data": [
            {
              "type": "sources",
              "id": "aerials-2016"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "type": "layers",
      "id": "aerials-2016",
      "attributes": {
        "style": {
          "id": "aerials-2016",
          "layout": {
            "visibility": "visible"
          },
          "source": "aerials-2016",
          "type": "raster",
          "metadata": {
            "nycplanninglabs:layergroupid": "aerials"
          }
        },
        "display-name": "2016",
        "before": "boundary_state"
      }
    },
    {
      "type": "sources",
      "id": "aerials-2016",
      "attributes": {
        "id": "aerials-2016",
        "type": "raster",
        "meta": {},
        "tiles": [
          "https:\/\/maps.nyc.gov\/xyz\/1.0.0\/photo\/2016\/{z}\/{x}\/{y}.png8"
        ],
        "tileSize": 256
      }
    },
  ]
}
```

</details>

I think we can get away with the API serializing the relationship this way even if it isn't explicitly done this way in our data structure (though it can be inferred). This means our serializers can do some special work to look up the source through the child `layer` keys.

**Comment by allthesignals** [comment]
Need to: 1) move metadata from layer-group into source 2) update serializers to lookup related sources through `layer`s and serve the information
