### ISSUE TITLE
July - Update MapPLUTO and monthly zoning data

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-layers-api#196]
EDM will let us know once the files have been uploaded to Carto.

The batch of files will include updated MapPLUTO data, along with all the usual zoning and DCM files.

- [x] Update CSV
- [x] Run python script
- [x] Update source json files with updated metadata dates
- [ ] Update data playbook (https://docs.google.com/document/d/1txHqKW-PCm3XIHrzR4xfJVhXvA3nOaf7r1v6XmDekbA/edit?usp=sharing)

**Comment by trbmcginnis** [comment]
This update will affect community profiles issue #601

**Comment by trbmcginnis** [comment]
Updated mappluto! Have yet to update the other datasets. Just noting this here in case someone needs to look at the status of this issue.
